# Generated by Django 5.1.1 on 2024-11-18 18:39

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_roll_no', models.CharField(default='unknown', max_length=20)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(default='Absent', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_roll_no', models.CharField(max_length=15)),
                ('meal', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_roll_no', models.CharField(max_length=20)),
                ('meal', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Present', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('branch', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], help_text='Select your branch', max_length=100)),
                ('uni_roll_no', models.CharField(help_text='Enter your University Roll Number', max_length=45, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter your name', max_length=45)),
                ('father_name', models.CharField(help_text="Enter your father's name", max_length=45)),
                ('father_phone_no', models.CharField(help_text="Enter your father's phone number (10 digits)", max_length=10, validators=[django.core.validators.RegexValidator(message="Father's phone number must be 10 digits.", regex='^\\d{10}$')])),
                ('phone_no', models.CharField(help_text='Enter your phone number (10 digits)', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')])),
                ('room_no', models.CharField(help_text='Enter your room number', max_length=45)),
                ('room_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple')], help_text='Select your room type', max_length=45)),
                ('hostel_type', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls')], help_text='Select your hostel type', max_length=45)),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Telangana', 'Telangana')], help_text='Select your state', max_length=45)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('qr_code_data', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
