# Generated by Django 5.1.1 on 2024-11-19 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father_phone_no',
            field=models.CharField(help_text="Enter your father's phone number (10 digits)", max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Father's phone number must be 10 digits.", regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.CharField(help_text='Enter your phone number (10 digits)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
