# Generated by Django 5.1.1 on 2024-11-19 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0002_alter_student_father_phone_no_alter_student_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uni_roll_no',
            field=models.CharField(help_text='Enter your University Roll Number (up to 7 digits)', max_length=7, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='University Roll Number must be a maximum of 7 digits and contain only numbers.', regex='^\\d{1,7}$')]),
        ),
    ]
