# Generated by Django 5.1.1 on 2024-11-19 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0003_alter_student_uni_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uni_roll_no',
            field=models.CharField(help_text='Enter your University Roll Number (up to 7 digits)', max_length=7, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="Father's phone number must be 10 digits.", regex='^\\d{7}$')]),
        ),
    ]
