# Generated by Django 5.1.1 on 2024-11-19 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0005_alter_student_uni_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uni_roll_no',
            field=models.CharField(help_text='Enter your University Roll Number (exactly 7 digits)', max_length=7, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='University Roll Number must be exactly 7 digits and contain only numbers.', regex='^\\d{7}$')]),
        ),
    ]
