# Generated by Django 5.1.1 on 2024-11-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0006_alter_student_uni_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default='Not provided', help_text='Enter your full address'),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='Unknown', help_text='Enter your city', max_length=100),
        ),
    ]
