# Generated by Django 5.1.1 on 2024-11-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0007_student_address_student_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(default=' ', help_text='Enter your full address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(default=' ', help_text='Enter your city', max_length=100),
        ),
    ]
