# Generated by Django 5.1.1 on 2026-07-19 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0008_alter_student_address_alter_student_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
