# Generated by Django 5.1.1 on 2026-07-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0009_remove_insecure_admin_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='qr_code',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
