# Generated by Django 5.1.1 on 2026-07-19 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0010_store_qr_in_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_rooms', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('double_rooms', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('triple_rooms', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('foursitter_rooms', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('single_capacity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('double_capacity', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('triple_capacity', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('foursitter_capacity', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hostel settings',
                'verbose_name_plural': 'Hostel settings',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='room_no',
            field=models.CharField(help_text='Select your room number', max_length=45),
        ),
        migrations.AlterField(
            model_name='student',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single (1 student)'), ('Double', 'Double (2 students)'), ('Triple', 'Triple (3 students)'), ('FourSitter', 'Four Sitter (4 students)')], help_text='Select your room type', max_length=45),
        ),
    ]
